/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplikasispp;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author asus
 */
public class FormSpp extends javax.swing.JInternalFrame {

    /** Creates new form FormSPP */
    public FormSpp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdSpp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNominal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpp = new javax.swing.JTable();

        jLabel1.setText("ID_SPP");

        txtIdSpp.setEnabled(false);

        jLabel2.setText("Tahun");

        jLabel3.setText("Nominal");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblSpp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSpp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSpp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIdSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNominal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdSpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    String sql = "INSERT INTO spp (tahun, nominal) VALUES (?,?)";
    java.sql.Connection conn = aplikasispp.Koneksi.configDB();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    pst.setString(1, txtTahun.getText());
    pst.setString(2, txtNominal.getText());
    
    pst.execute();
    javax.swing.JOptionPane.showMessageDialog(null, "Tarif SPP Berhasil Disimpan!");
    tampil_data();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
    String sql ="UPDATE spp SET tahun = ?, nominal = ? WHERE id_spp = ?";
    java.sql.Connection conn = aplikasispp.Koneksi.configDB();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    pst.setString(1, txtTahun.getText());
    pst.setString(2, txtNominal.getText());
    pst.setString(3, txtIdSpp.getText()); // Menggunakan ID sebagai kunci
    
    pst.execute();
    javax.swing.JOptionPane.showMessageDialog(null, "Data Tarif SPP Berhasil Diubah!");
    tampil_data();
    kosongkan_form();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
    String sql ="DELETE FROM spp WHERE id_spp = ?";
    java.sql.Connection conn = aplikasispp.Koneksi.configDB();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, txtIdSpp.getText());
    
    pst.execute();
    javax.swing.JOptionPane.showMessageDialog(this, "Data Tarif SPP Berhasil Dihapus!");
    tampil_data();
    kosongkan_form();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblSppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSppMouseClicked
int baris = tblSpp.getSelectedRow();
txtIdSpp.setText(tblSpp.getValueAt(baris, 0).toString());
txtTahun.setText(tblSpp.getValueAt(baris, 1).toString());
txtNominal.setText(tblSpp.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_tblSppMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
kosongkan_form();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSpp;
    private javax.swing.JTextField txtIdSpp;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
private void tampil_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID SPP");
    model.addColumn("Tahun");
    model.addColumn("Nominal");
    
    try {
        String sql = "SELECT * FROM spp";
        java.sql.Connection conn = aplikasispp.Koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while(res.next()){
            model.addRow(new Object[]{
                res.getString("id_spp"),
                res.getString("tahun"),
                res.getString("nominal")
            });
        }
        tblSpp.setModel(model);
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}
private void kosongkan_form(){
    txtIdSpp.setText("");
    txtTahun.setText("");
    txtNominal.setText("");
    txtTahun.requestFocus();
}
}
